name: 'fivethirtyeight'
version: '0.1.0'
require-dbt-version: ">=0.14.0"

profile: "snowflake-immutable"

data-paths: ["data"]
log-path: "logs"

target-path: "target"
clean-targets: ["target", "dbt_modules"]

seeds:
  enabled: false
  quote_columns: true

  fivethirtyeight:
    hip_hop_candidate_lyrics:
      enabled: true
    librarians:
      enabled: true
    pew_religions:
      enabled: true